"use client";

import type { Metadata } from "next";
import React from "react";
import { Inter } from "next/font/google";

import "./globals.css";
import "@mantine/core/styles.css";
import { ColorSchemeScript, MantineProvider } from "@mantine/core";
import Navbar from "@/components/Navbar/Navbar";
import { Provider } from "react-redux";
import store from "@/store/store";
import Providers from "@/Context/Providers";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body style={{ display: "flex", flexDirection: "row" }}>
        <Providers>
          <Provider store={store}>
            <MantineProvider>
              <Navbar />

              <main>{children}</main>
            </MantineProvider>
          </Provider>
        </Providers>
      </body>
    </html>
  );
}
